repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.1.2
    hooks:
      - id: biome-check
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: check-xml
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args: [--branch, master]
